import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

// NOTE: for the meta data we should use the metadata api.
// and should not use the head tag. (recommended by next js)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// NOTE: This layout is a server layout and it cna't be used in client side.
// This is a mandatory file in next js.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
